version: '3.3'

services:
  node-api:
    build:
      context: ./node-api
    ports:
      - "4000:4000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  python-consumer:
    build:
      context: ./python-consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_URI=mongodb://curious_4846:h1JsBpP9SO7OF5Et@ac-ja4zzhv-shard-00-00.konyvse.mongodb.net:27017,ac-ja4zzhv-shard-00-01.konyvse.mongodb.net:27017,ac-ja4zzhv-shard-00-02.konyvse.mongodb.net:27017/?ssl=true&replicaSet=atlas-6zqiak-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster0

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
